eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9110/eureka
  instance:
    hostname: localhost


microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/paymentservice
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/paymentservice
